#!/bin/bash

# Get the commit message
commit_msg=$(cat $1)

# Define a regex pattern to match the conventional commit message format declared in README
pattern='^(ADD|DELETE|MERGE|FIX|REFACTOR|CHORE|DOCS|REVERT|CONFIG|STYLE|TEST)(\([a-z]+\))?!?: .+$'

# Test if the commit message matches the pattern
if ! [[ $commit_msg =~ $pattern ]]; then
  echo "ERROR: The commit message does not match the Conventional Commits format."
  echo ""
  echo "       Written keyword is not a keyword in declared convention"
  echo "       All commit messages should be in english"
  echo "       Example: "ADD: new client component""
  echo "       Opening Convention..."
  code -g README.md:115

  exit 1
fi

# If the commit message matches the pattern, exit successfully hola
exit 0